version: "3.7"

services:
    otoha:
        image: jlesage/firefox
        container_name: mitm_otoha
        restart: always
        volumes:
            - /dev/shm:/dev/shm
        ports:
            - "5800:5800"
        networks:
            - mitm
    milad:
        image: aikain/simplehttpserver:0.1
        container_name: mitm_milad
        restart: always
        volumes:
            - ./milad_files:/var/www
        networks:
            - mitm
    jeff:
        privileged: true
        build: .
        container_name: mitm_jeff
        volumes:
            - ./jeff_files:/demo
        sysctls:
            # Necessary for transparent mode for mitmproxy
            - net.ipv4.ip_forward=1
            - net.ipv6.conf.all.forwarding=1
            - net.ipv4.conf.all.send_redirects=0
        networks:
            - mitm

networks:
    mitm:
